java -classpath ".\SendMail.jar;.\mail.jar;.\activation.jar;.\rt.jar" SendMail SMTP.NEXLINX.NET.PK 25 IRFAN.KHAN irfan.khan IRFAN.KHAN@SOFTECH.COM.PK "IRFAN_KULACHI@YAHOO.COM|012305-115433|BBGN/KURA AFRICA FUND|C/O DATABANK BROKERAGE LTDPMB MINISTRIES|IRFAN_KULACHI@YAHOO.COM;MIRFANGANDAPUR@GMAIL.COM" "TESTING" "IGNORE IT YAAR" ".\ParametersList.txt" SENDMAIL.LOG 0
@pause
